Class {
	#name : 'AoCDay06Test',
	#superclass : 'AoCBaseTest',
	#category : 'AoC2022-Tests',
	#package : 'AoC2022-Tests'
}

{ #category : 'running' }
AoCDay06Test >> setUp [
	super setUp.
	self day: '6'.
	self path: FileLocator home / 'Projects' / 'adventofcode2022' asString.

	inst := AoCDay06 new.
]

{ #category : 'tests' }
AoCDay06Test >> testPart1WithRealData [
|lines res|

	lines := self
		         readInputFileAsLines: 'input1.txt'
		         for: self day
		         onPath: self path.

	res := inst part1: lines.

	self assert: res equals: 1531.
]

{ #category : 'tests' }
AoCDay06Test >> testPart1WithSample [
|lines res|

	lines := self
		         readInputFileAsLines: 'input0.txt'
		         for: self day
		         onPath: self path.

	res := inst part1: lines.

	self assert: res equals: 7.
]

{ #category : 'tests' }
AoCDay06Test >> testPart2WithRealData [
|lines res|

	lines := self
		         readInputFileAsLines: 'input1.txt'
		         for: self day
		         onPath: self path.

	res := inst part2: lines.

	self assert: res equals: 2518.
]

{ #category : 'tests' }
AoCDay06Test >> testPart2WithSample [
|lines res|

	lines := self
		         readInputFileAsLines: 'input0.txt'
		         for: self day
		         onPath: self path.

	res := inst part2: lines.

	self assert: res equals: 19.
]
